version: "3.8"

networks:
  sideByDocker:
    driver: bridge

volumes:
  mysql-data:

services:

  webserver:
    container_name: webserver
    working_dir: /app
    networks:
      - sideByDocker
    restart: unless-stopped
    depends_on:
      - app
      - db
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public

  app:
    container_name: app
    networks:
      - sideByDocker
    restart: unless-stopped
    depends_on:
      - db
    build: _docker/php-fpm
    volumes:
      - ./:/app

  composer:
    container_name: composer
    networks:
      - sideByDocker
    depends_on:
      - app
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs --no-interaction && \
              composer dump-autoload

  db:
    container_name: db
    networks:
      - sideByDocker
    restart: unless-stopped
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - ${MYSQL_ROOT_PASSWORD}
      - ${MYSQL_USER}
      - ${MYSQL_PASSWORD}
      - ${MYSQL_DATABASE}

  pma:
    container_name: pma
    networks:
      - sideByDocker
    restart: unless-stopped
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      - ${PMA_HOST}
